//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBcfaSystemEntitiesData : DbContext
    {
        public dbBcfaSystemEntitiesData()
            : base("name=dbBcfaSystemEntitiesData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<SubjectList> SubjectLists { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<tblStudentInformation> tblStudentInformations { get; set; }
        public virtual DbSet<tblSchoolYear> tblSchoolYears { get; set; }
        public virtual DbSet<tblEnrollment> tblEnrollments { get; set; }
        public virtual DbSet<tblRequirement> tblRequirements { get; set; }
        public virtual DbSet<tblSchedule> tblSchedules { get; set; }
        public virtual DbSet<tblSection> tblSections { get; set; }
    }
}
