//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectList
    {
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public string SubjectType { get; set; }
        public string SubjectTeacher { get; set; }
    }
}
