//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnrollment
    {
        public int id { get; set; }
        public string AcademicYear { get; set; }
        public string EnrollmentID { get; set; }
        public string StudentID { get; set; }
        public string NameOfStudent { get; set; }
        public string StudentType { get; set; }
        public string Status { get; set; }
        public string GradeLevel { get; set; }
        public string Section { get; set; }
        public string DateEnrolled { get; set; }
    }
}
