//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequirement
    {
        public string StudentID { get; set; }
        public string Name { get; set; }
        public bool Form137 { get; set; }
        public bool NSO { get; set; }
        public bool GoodMoral { get; set; }
        public bool GradeCard { get; set; }
    }
}
