//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedule
    {
        public int SchedID { get; set; }
        public string AcademicYear { get; set; }
        public string Type { get; set; }
        public string GradeLevel { get; set; }
        public string Section { get; set; }
        public string Adviser { get; set; }
        public string SubjectCode { get; set; }
        public string DescriptiveTitle { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public string TeacherID { get; set; }
        public string Teacher { get; set; }
    }
}
