//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentInformation
    {
        public string StudentID { get; set; }
        public string StType { get; set; }
        public string StLastName { get; set; }
        public string StFirstName { get; set; }
        public string StMiddleName { get; set; }
        public Nullable<int> StAge { get; set; }
        public string StDateOfBirth { get; set; }
        public string StPlaceOfBirth { get; set; }
        public string StContact { get; set; }
        public string StGender { get; set; }
        public string StMaritalStatus { get; set; }
        public string StCitizenship { get; set; }
        public string StReligion { get; set; }
        public string StAddress { get; set; }
        public string StFatherName { get; set; }
        public string StFatherOccupation { get; set; }
        public string StMotherName { get; set; }
        public string StMotherOccupation { get; set; }
        public string StParentAddress { get; set; }
        public string StElemSchool { get; set; }
        public string StElemAddress { get; set; }
        public string StHighSchool { get; set; }
        public string StHighAddress { get; set; }
    }
}
