//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollBCFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSection
    {
        public string SType { get; set; }
        public int SectionID { get; set; }
        public string GradeLevel { get; set; }
        public string SectionName { get; set; }
        public string SectionAdviser { get; set; }
    }
}
